package pojo;

// Generated 13 Feb, 2023 4:39:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Courses generated by hbm2java
 */
@Entity
@Table(name = "courses", catalog = "driving_school")
public class Courses implements java.io.Serializable {

	private Integer id;
	private String courses;
	private String price;
	private String time;
	private String image;

	public Courses() {
	}

	public Courses(String courses, String price, String time, String image) {
		this.courses = courses;
		this.price = price;
		this.time = time;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "courses", length = 100)
	public String getCourses() {
		return this.courses;
	}

	public void setCourses(String courses) {
		this.courses = courses;
	}

	@Column(name = "price", length = 100)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "time", length = 50)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
